import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import clsx from 'clsx'
import styles from './Changelog.module.css'

/**
 * public/changelog.json is GENERATED by the advizr-admin patch-notes
 * publisher (v2 envelope) — never hand-edit it; the master-DB patch_notes
 * table is canonical and the file is fully rewritten on every publish.
 * `slug` is the public anchor id AND the RSS guid (see
 * app/changelog.xml/route.ts — both consume it verbatim, no derivation).
 */
interface ChangelogEntry {
  slug: string
  date: string
  title: string
  summary: string
  body_md: string | null
  category: 'feature' | 'improvement' | 'fix' | 'breaking'
  product_areas: string[]
  version: string | null
}

interface ChangelogFile {
  version: number
  entries: ChangelogEntry[]
}

const categoryLabels: Record<string, string> = {
  feature: 'Feature',
  improvement: 'Improvement',
  fix: 'Fix',
  breaking: 'Breaking',
}

const categoryStyles: Record<string, string> = {
  feature: styles.catFeature,
  improvement: styles.catImprovement,
  fix: styles.catFix,
  breaking: styles.catBreaking,
}

function formatDate(iso: string): string {
  const date = new Date(iso + 'T00:00:00')
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

// Server component: the JSON is read at build/render time so entry data
// never ships in the client bundle.
function loadEntries(): ChangelogEntry[] {
  const raw = readFileSync(join(process.cwd(), 'public', 'changelog.json'), 'utf8')
  const parsed = JSON.parse(raw) as ChangelogFile
  return parsed.entries.slice().sort((a, b) => b.date.localeCompare(a.date))
}

interface ChangelogProps {
  className?: string
}

export function Changelog({ className }: ChangelogProps) {
  const entries = loadEntries()

  return (
    <div className={clsx(styles.changelog, className)}>
      {entries.map((entry) => (
        <article key={entry.slug} id={entry.slug} className={styles.entry}>
          <div className={styles.rail}>
            <time className={styles.date} dateTime={entry.date}>
              {formatDate(entry.date)}
            </time>
            {entry.version && <span className={styles.version}>v{entry.version}</span>}
          </div>
          <div className={styles.track} aria-hidden="true">
            <span className={styles.dot} />
          </div>
          <div className={styles.card}>
            <div className={styles.cardHeader}>
              <h3 className={styles.title}>
                <a href={`#${entry.slug}`} className={styles.permalink}>
                  {entry.title}
                  <span className={styles.hash} aria-hidden="true">
                    #
                  </span>
                </a>
              </h3>
              <span className={clsx(styles.tag, categoryStyles[entry.category])}>
                {categoryLabels[entry.category] || entry.category}
              </span>
            </div>
            {/* body_md is rendered by the redesigned patch-notes surface
                (Instrument Grade shell); this interim card shows the summary. */}
            <p className={styles.description}>{entry.summary}</p>
          </div>
        </article>
      ))}
      <a href="/changelog.xml" className={styles.rssLink}>
        Subscribe via RSS
      </a>
    </div>
  )
}
