import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { ComponentType } from 'react'
import Markdown, { type Components } from 'react-markdown'
import remarkGfm from 'remark-gfm'

import { mdxThemeComponents } from '@/components/mdx-theme'
import { RefCode } from '@/components/ui/ref-code'
import { cn } from '@/lib/cn'

/**
 * Changelog — the public patch-notes stream (PR-E, adoption-map §7 BINDING).
 *
 * Server component over public/changelog.json (v2 envelope, GENERATED by the
 * advizr-admin patch-notes publisher — never hand-edit). Anatomy: Notion's
 * two-column release grid (rail 1fr / body 2fr, sticky mono dates ≥md) with
 * Linear's ledger skeleton — a DimensionLine rail carrying one StatusGlyph
 * per entry (square = release, diamond = breaking, newest filled --signal),
 * REL-#### RefCodes derived from date order (oldest = REL-0001, stable
 * across publishes), hover-reveal permalinks, ~3s :target highlight
 * (styles/prose.css), and `## Fixes` / `## Improvements` sections of body_md
 * folded into collapsed native-<details> ledgers. <md the rail collapses to
 * an inline glyph · date · REL header row per entry (§6.3).
 */

/* ------------------------------------------------------------------ */
/*  Data                                                               */
/* ------------------------------------------------------------------ */

interface ChangelogEntry {
  slug: string
  date: string
  title: string
  summary: string
  body_md: string | null
  category: string
  product_areas: string[]
  version: string | null
}

interface ChangelogFile {
  version: number
  entries: ChangelogEntry[]
}

// Server component: the JSON is read at build/render time so entry data
// never ships in the client bundle.
function loadEntries(): ChangelogEntry[] {
  const raw = readFileSync(join(process.cwd(), 'public', 'changelog.json'), 'utf8')
  return (JSON.parse(raw) as ChangelogFile).entries
    .slice()
    .sort((a, b) => b.date.localeCompare(a.date) || b.slug.localeCompare(a.slug))
}

/** REL-#### numbering: oldest entry = REL-0001, ascending by date (slug as
 *  tie-break) — appending newer entries never renumbers older ones. */
function relNumbers(entries: ChangelogEntry[]): Map<string, number> {
  const ascending = entries
    .slice()
    .sort((a, b) => a.date.localeCompare(b.date) || a.slug.localeCompare(b.slug))
  return new Map(ascending.map((entry, i) => [entry.slug, i + 1]))
}

function formatDate(iso: string): string {
  return new Date(`${iso}T00:00:00`).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

/* ------------------------------------------------------------------ */
/*  body_md rendering                                                  */
/* ------------------------------------------------------------------ */

type Segment =
  | { kind: 'prose'; md: string }
  | { kind: 'ledger'; title: string; md: string; count: number }

/** Split body_md on `## Fixes` / `## Improvements` headings — those sections
 *  fold into collapsed ledgers; everything else renders as prose. */
function splitBody(body: string): Segment[] {
  const segments: Segment[] = []
  let buffer: string[] = []
  let ledgerTitle: string | null = null

  const flush = () => {
    const md = buffer.join('\n').trim()
    if (ledgerTitle) {
      const count = buffer.filter((line) => /^\s*[-*+]\s+/.test(line)).length
      segments.push({ kind: 'ledger', title: ledgerTitle, md, count })
    } else if (md) {
      segments.push({ kind: 'prose', md })
    }
    buffer = []
  }

  for (const line of body.split(/\r?\n/)) {
    const ledgerHead = line.match(/^##\s+(Fixes|Improvements)\s*$/)
    if (ledgerHead) {
      flush()
      ledgerTitle = ledgerHead[1]
      continue
    }
    if (ledgerTitle && /^##\s+/.test(line)) {
      flush()
      ledgerTitle = null
    }
    buffer.push(line)
  }
  flush()
  return segments
}

/** react-markdown hands components a `node` prop the DOM must never see. */
function adapt<P extends object>(Component: ComponentType<P>) {
  return function Adapted({ node: _node, ...props }: { node?: unknown } & P) {
    return <Component {...(props as P)} />
  }
}

// Prose segments reuse the mdx-theme element skins (same treatments as MDX
// pages). Entry titles are h2, so body headings step down one level to keep
// the page outline sane.
const bodyComponents: Components = {
  a: adapt(mdxThemeComponents.a),
  blockquote: adapt(mdxThemeComponents.blockquote),
  code: adapt(mdxThemeComponents.code),
  h1: adapt(mdxThemeComponents.h3),
  h2: adapt(mdxThemeComponents.h3),
  h3: adapt(mdxThemeComponents.h4),
  h4: adapt(mdxThemeComponents.h4),
  h5: adapt(mdxThemeComponents.h5),
  h6: adapt(mdxThemeComponents.h6),
  hr: adapt(mdxThemeComponents.hr),
  img: adapt(mdxThemeComponents.img),
  li: adapt(mdxThemeComponents.li),
  ol: adapt(mdxThemeComponents.ol),
  pre: adapt(mdxThemeComponents.pre),
  table: adapt(mdxThemeComponents.table),
  td: adapt(mdxThemeComponents.td),
  th: adapt(mdxThemeComponents.th),
  tr: adapt(mdxThemeComponents.tr),
  ul: adapt(mdxThemeComponents.ul),
}

// Folded ledger sections: list items become hairline ledger rows — square
// glyph + optional mono area label (a bold lead-in, e.g. `**Portal** …`,
// renders as the PORTAL-style label) + one plain sentence.
const ledgerComponents: Components = {
  ...bodyComponents,
  ul: ({ node: _node, className: _c, ...props }) => (
    <ul className="m-0 list-none divide-y divide-border p-0" {...props} />
  ),
  ol: ({ node: _node, className: _c, ...props }) => (
    <ol className="m-0 list-none divide-y divide-border p-0" {...props} />
  ),
  li: ({ node: _node, className: _c, children, ...props }) => (
    <li
      className="flex items-start gap-2.5 px-4 py-2.5 text-[0.8125rem] leading-relaxed text-[hsl(var(--text-2))]"
      {...props}
    >
      <span aria-hidden="true" className="mt-[0.4em] size-2 shrink-0 bg-[hsl(var(--text-4))]" />
      <span className="min-w-0">{children}</span>
    </li>
  ),
  p: ({ node: _node, className: _c, ...props }) => (
    <p className="m-0 px-4 py-2.5 text-[0.8125rem] text-[hsl(var(--text-2))]" {...props} />
  ),
  strong: ({ node: _node, className: _c, ...props }) => (
    <strong
      className="mr-1 font-mono text-[10.5px] font-normal uppercase tracking-[0.08em] text-[hsl(var(--text-3))]"
      {...props}
    />
  ),
}

function LedgerSection({ title, md, count }: { title: string; md: string; count: number }) {
  return (
    <details className="group/ledger my-4 border border-border bg-[hsl(var(--card))]">
      <summary
        className={cn(
          'flex min-h-10 cursor-pointer select-none list-none items-center gap-2.5 px-4 py-2 [&::-webkit-details-marker]:hidden',
          'transition-[background-color] duration-150 ease-out hover:bg-[hsl(var(--secondary))] hover:duration-0 motion-reduce:transition-none',
          'focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-[hsl(var(--signal))]'
        )}
      >
        <span
          aria-hidden="true"
          className="flex size-4 shrink-0 items-center justify-center border border-border font-mono text-[11px] leading-none text-[hsl(var(--text-3))]"
        >
          <span className="group-open/ledger:hidden">+</span>
          <span className="hidden group-open/ledger:inline">−</span>
        </span>
        <span className="font-mono text-[11px] uppercase tracking-[0.08em] text-[hsl(var(--text-2))]">
          {title} ({count})
        </span>
      </summary>
      <div className="border-t border-border group-open/ledger:animate-[docs-details-fade_150ms_ease-out]">
        <Markdown remarkPlugins={[remarkGfm]} components={ledgerComponents}>
          {md}
        </Markdown>
      </div>
    </details>
  )
}

function EntryBody({ body }: { body: string }) {
  return (
    <div className="mt-5">
      {splitBody(body).map((segment, i) =>
        segment.kind === 'prose' ? (
          <Markdown key={i} remarkPlugins={[remarkGfm]} components={bodyComponents}>
            {segment.md}
          </Markdown>
        ) : (
          <LedgerSection key={i} title={segment.title} md={segment.md} count={segment.count} />
        )
      )}
    </div>
  )
}

/* ------------------------------------------------------------------ */
/*  Entry chrome                                                       */
/* ------------------------------------------------------------------ */

/** Rail glyph — StatusGlyph vocabulary: square = release, diamond =
 *  breaking; the NEWEST entry's glyph is the one filled --signal mark. */
function EntryGlyph({
  breaking,
  newest,
  className,
}: {
  breaking: boolean
  newest: boolean
  className?: string
}) {
  return (
    <span
      aria-hidden="true"
      className={cn(
        'block size-2.5 shrink-0',
        breaking && 'rotate-45',
        newest
          ? 'bg-[hsl(var(--signal))]'
          : 'border border-[hsl(var(--text-3))] bg-[hsl(var(--background))]',
        className
      )}
    />
  )
}

/** Square mono category chip — hairline frame; breaking gets the semantic
 *  2px signal edge (never a tinted fill). */
function CategoryChip({ category }: { category: string }) {
  const breaking = category === 'breaking'
  return (
    <span
      className={cn(
        'inline-flex items-center border border-border px-1.5 py-1 font-mono text-[10px] uppercase leading-none tracking-[0.08em] text-[hsl(var(--text-3))]',
        breaking && 'border-l-2 border-l-[hsl(var(--signal))] text-[hsl(var(--text-2))]'
      )}
    >
      {category}
    </span>
  )
}

function VersionChip({ version }: { version: string }) {
  return (
    <span className="inline-flex items-center border border-border px-1.5 py-1 font-mono font-tabular text-[10px] leading-none tracking-[0.04em] text-[hsl(var(--text-3))]">
      v{version}
    </span>
  )
}

const dateClass =
  'font-mono font-tabular text-[0.8125rem] uppercase leading-tight tracking-[0.04em] text-[hsl(var(--text-2))]'

function Entry({
  entry,
  rel,
  newest,
}: {
  entry: ChangelogEntry
  rel: number
  newest: boolean
}) {
  const breaking = entry.category === 'breaking'

  return (
    <article
      id={entry.slug}
      className={cn(
        'changelog-entry relative grid scroll-mt-[calc(var(--topbar-height)+1.5rem)] gap-y-5 border-t border-border pb-16 pt-8',
        'md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)] md:gap-x-10'
      )}
    >
      {/* ≥md rail: DimensionLine + glyph + sticky date / version / REL ref */}
      <div className="relative hidden md:block">
        <span
          aria-hidden="true"
          className="absolute inset-y-1 left-[5px] w-px bg-[hsl(var(--border))]"
        />
        <EntryGlyph breaking={breaking} newest={newest} className="absolute left-px top-1.5" />
        <div className="sticky top-[calc(var(--topbar-height)+2rem)] flex flex-col items-start gap-2 pl-7">
          <time dateTime={entry.date} className={dateClass}>
            {formatDate(entry.date)}
          </time>
          {entry.version && <VersionChip version={entry.version} />}
          <RefCode kind="REL" id={rel} href={`#${entry.slug}`} />
        </div>
      </div>

      {/* <md: the rail collapses to an inline header row (§6.3) */}
      <div className="flex flex-col gap-3 md:hidden">
        <div className="flex flex-wrap items-center gap-3">
          <EntryGlyph breaking={breaking} newest={newest} />
          <time dateTime={entry.date} className={dateClass}>
            {formatDate(entry.date)}
          </time>
          {entry.version && <VersionChip version={entry.version} />}
          <RefCode kind="REL" id={rel} />
        </div>
        <span aria-hidden="true" className="block h-px w-8 bg-[hsl(var(--border))]" />
      </div>

      <div className="min-w-0">
        <h2 className="group/heading m-0 text-[1.3125rem] font-semibold leading-snug text-[hsl(var(--text-1))]">
          <a href={`#${entry.slug}`} className="text-inherit no-underline">
            {entry.title}
          </a>
          <a
            href={`#${entry.slug}`}
            aria-label="Link to this entry"
            data-heading-anchor
            data-pagefind-ignore
            className={cn(
              'ml-2 font-mono text-[0.75em] font-normal text-[hsl(var(--text-3))] no-underline',
              'opacity-0 transition-opacity duration-150 ease-out',
              'group-hover/heading:opacity-100 group-hover/heading:duration-0 focus-visible:opacity-100 motion-reduce:transition-none'
            )}
          >
            #
          </a>
        </h2>
        <div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1.5">
          <CategoryChip category={entry.category} />
          {entry.product_areas.map((area) => (
            <span
              key={area}
              className="font-mono text-[10.5px] uppercase tracking-[0.08em] text-[hsl(var(--text-3))]"
            >
              {area}
            </span>
          ))}
        </div>
        <p className="mb-0 mt-4 text-[0.9375rem] leading-[1.7] text-[hsl(var(--text-2))]">
          {entry.summary}
        </p>
        {entry.body_md && <EntryBody body={entry.body_md} />}
      </div>
    </article>
  )
}

/* ------------------------------------------------------------------ */
/*  Page stream                                                        */
/* ------------------------------------------------------------------ */

const PAGE_SIZE = 10

interface ChangelogProps {
  className?: string
}

export function Changelog({ className }: ChangelogProps) {
  const entries = loadEntries()
  const rel = relNumbers(entries)

  if (entries.length === 0) {
    return (
      <div className={cn('my-8 border border-border px-6 py-10 text-center', className)}>
        <span className="inline-flex items-center border border-border px-2 py-1 font-mono text-[11px] tracking-[0.08em] text-[hsl(var(--text-3))]">
          REL-0000
        </span>
        <p className="mb-0 mt-4 text-[0.9375rem] text-[hsl(var(--text-2))]">
          No updates published yet — the first patch note lands here.
        </p>
      </div>
    )
  }

  const visible = entries.slice(0, PAGE_SIZE)
  const older = entries.slice(PAGE_SIZE)

  return (
    <div className={cn('mt-10', className)}>
      {visible.map((entry, i) => (
        <Entry key={entry.slug} entry={entry} rel={rel.get(entry.slug)!} newest={i === 0} />
      ))}

      {older.length > 0 && (
        <details className="group/older border-t border-border">
          <summary
            className={cn(
              'flex min-h-12 cursor-pointer select-none list-none items-center gap-2.5 [&::-webkit-details-marker]:hidden',
              'focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-[hsl(var(--signal))]'
            )}
          >
            <span
              aria-hidden="true"
              className="flex size-4 shrink-0 items-center justify-center border border-border font-mono text-[11px] leading-none text-[hsl(var(--text-3))]"
            >
              <span className="group-open/older:hidden">+</span>
              <span className="hidden group-open/older:inline">−</span>
            </span>
            <span className="font-mono text-[11px] uppercase tracking-[0.08em] text-[hsl(var(--text-2))]">
              Older updates ({older.length})
            </span>
          </summary>
          {older.map((entry) => (
            <Entry key={entry.slug} entry={entry} rel={rel.get(entry.slug)!} newest={false} />
          ))}
        </details>
      )}

      <div className="hairline-t flex items-center pt-6">
        <a
          href="/changelog.xml"
          className={cn(
            'inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.08em] text-[hsl(var(--text-3))] no-underline',
            'transition-[color] duration-150 ease-out hover:text-[hsl(var(--text-1))] hover:duration-0 motion-reduce:transition-none'
          )}
        >
          <span aria-hidden="true" className="port-dot" />
          Subscribe via RSS
        </a>
      </div>
    </div>
  )
}
