import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

export const dynamic = 'force-static'

const SITE_URL = 'https://docs.advizr.ca'
const CHANGELOG_URL = `${SITE_URL}/docs/resources/changelog`

/**
 * public/changelog.json is GENERATED by the advizr-admin patch-notes
 * publisher (v2 envelope). `slug` is consumed verbatim as the guid — the
 * old title+date derivation is gone (the publisher owns slug creation, and
 * seeded legacy entries kept their historical values, so existing guids
 * were not disturbed by the v2 cutover).
 */
interface ChangelogEntry {
  slug: string
  date: string
  title: string
  summary: string
  category: string
  product_areas: string[]
  version: string | null
}

interface ChangelogFile {
  version: number
  entries: ChangelogEntry[]
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function toPubDate(isoDate: string): string {
  return new Date(`${isoDate}T00:00:00Z`).toUTCString()
}

export async function GET() {
  const raw = await readFile(join(process.cwd(), 'public', 'changelog.json'), 'utf8')
  const entries = (JSON.parse(raw) as ChangelogFile).entries
    .slice()
    .sort((a, b) => b.date.localeCompare(a.date))

  const items = entries
    .map((entry) => {
      const permalink = `${CHANGELOG_URL}#${entry.slug}`
      const title = entry.version ? `${entry.title} (v${entry.version})` : entry.title
      const categories = [entry.category, ...entry.product_areas]
        .map((c) => `      <category>${escapeXml(c)}</category>`)
        .join('\n')
      return [
        '    <item>',
        `      <title>${escapeXml(title)}</title>`,
        `      <link>${escapeXml(permalink)}</link>`,
        `      <guid isPermaLink="true">${escapeXml(permalink)}</guid>`,
        `      <description>${escapeXml(entry.summary)}</description>`,
        categories,
        `      <pubDate>${toPubDate(entry.date)}</pubDate>`,
        '    </item>',
      ].join('\n')
    })
    .join('\n')

  const lastBuildDate = entries.length > 0 ? toPubDate(entries[0].date) : new Date().toUTCString()

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Advizr Changelog</title>
    <link>${CHANGELOG_URL}</link>
    <description>Updates to the Advizr platform, documentation, and services.</description>
    <language>en</language>
    <lastBuildDate>${lastBuildDate}</lastBuildDate>
    <atom:link href="${SITE_URL}/changelog.xml" rel="self" type="application/rss+xml"/>
${items}
  </channel>
</rss>
`

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
    },
  })
}
