import type { LucideIcon } from 'lucide-react'
import {
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  CircleHelp,
  ClipboardList,
  Compass,
  CreditCard,
  Database,
  FileText,
  GitBranch,
  GraduationCap,
  Home,
  Layers,
  Library,
  Lightbulb,
  Lock,
  LockKeyhole,
  Mail,
  MessageCircle,
  PenLine,
  Plug,
  Rocket,
  Ruler,
  Search,
  Settings2,
  Shield,
  Sparkles,
  Sprout,
  Target,
  TrendingUp,
  Users,
  Workflow,
  Wrench,
  Zap,
} from 'lucide-react'

/**
 * Curated icon registry for MDX content.
 *
 * Content authors pass a string name (e.g. <Card icon="rocket" />) and the
 * design system controls rendering: consistent size, stroke, and the tinted
 * IconBox container. Emoji are banned in icon props — the design-gates spec
 * enforces this on rendered pages.
 */
export const iconRegistry: Record<string, LucideIcon> = {
  'bar-chart': BarChart3,
  bell: Bell,
  'book-open': BookOpen,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  'circle-help': CircleHelp,
  'clipboard-list': ClipboardList,
  compass: Compass,
  'credit-card': CreditCard,
  database: Database,
  'file-text': FileText,
  'git-branch': GitBranch,
  'graduation-cap': GraduationCap,
  home: Home,
  layers: Layers,
  library: Library,
  lightbulb: Lightbulb,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  mail: Mail,
  'message-circle': MessageCircle,
  'pen-line': PenLine,
  plug: Plug,
  rocket: Rocket,
  ruler: Ruler,
  search: Search,
  settings: Settings2,
  shield: Shield,
  sparkles: Sparkles,
  sprout: Sprout,
  target: Target,
  'trending-up': TrendingUp,
  users: Users,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
}

export type IconName = keyof typeof iconRegistry
